services:
  catalog.service:
    image: catalog.service
    container_name: catalog-service
    build:
      context: Catalog.Service
      dockerfile: Dockerfile
    ports:
      - "5276:8080"
    environment:
      - MongoDbSettings__Host=mongodb
    networks:
      - catalog-network
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - catalog-network
    restart: unless-stopped

networks:
  catalog-network:
    driver: bridge

volumes:
  mongodb-data:
    