@hostAddress = https://localhost:5002
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjhERENDQTBBOTc4N0VBQUUxQUJBNEQzQTE0MTBGMjE0IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDA1IiwibmJmIjoxNzc0NDM5MjY5LCJpYXQiOjE3NzQ0MzkyNjksImV4cCI6MTc3NDQ0Mjg2OSwiYXVkIjpbImNhdGFsb2ciLCJpbnZlbnRvcnkiXSwic2NvcGUiOlsiY2F0YWxvZy5mdWxsYWNjZXNzIiwiaW52ZW50b3J5LmZ1bGxhY2Nlc3MiLCJvcGVuaWQiLCJwcm9maWxlIl0sImFtciI6WyJwd2QiXSwiY2xpZW50X2lkIjoicG9zdG1hbiIsInN1YiI6IjExY2NjMjFmLTE5Y2MtNDljMi04Y2FjLWY2YmU2ZWZhNmE0NiIsImF1dGhfdGltZSI6MTc3NDQzOTI2OSwiaWRwIjoibG9jYWwiLCJqdGkiOiIxMjE1MzI0NjNGMDA5RThCNjJERUVGRENEMEVGMzAwNyJ9.g79E08anFtoaOn4GiRia0cHMacueEvzusHJq5PK8JgH59FSkXLjWT0o90mPLjmBNV9QhJE_SlUWMcF4pbKM3U-qTt1B30xjIc5bApVJ7W9Q8DAACc6gaDlWzDOVAn2z55xknxUB2RhsMKuuaialnwQYhxeJZKsR6Jl_LR2ifeOcSlN6RkrjH1LuLuWxre3ndIVFfI8_M4SBSTcTp_oWQyZVhaTZpUzMELBoDWLwzDhtUmEPkMQwANeAXbXi-Py74m5m8zZhI0HlDOv79Xh4IGJq2g6vIJU3vLCQq0pzHeQu7M_QQV8h80McE79rC8s28WtPMl58s6z0dkEho03I0IQ


###
POST {{hostAddress}}/items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ "userId": "D9BFCB35-696A-42FD-9D64-75440635F467", "catalogItemId": "D9BFCB35-696A-42FD-9D64-75440635F467", "quantity": 5 }

